# Generated by Django 5.2.1 on 2025-06-03 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_str', models.CharField(max_length=255, verbose_name='Función Ingresada')),
                ('method', models.CharField(choices=[('bisection', 'Bisección'), ('newton_raphson', 'Newton-Raphson'), ('modified_newton_raphson', 'Newton-Raphson Modificado')], max_length=30, verbose_name='Método Utilizado')),
                ('inputs_used', models.CharField(max_length=255, verbose_name='Parámetros de Entrada')),
                ('result', models.FloatField(blank=True, null=True, verbose_name='Raíz Encontrada')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Historial de Cálculo',
                'verbose_name_plural': 'Historial de Cálculos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
