# Generated by Django 5.2.1 on 2025-06-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculationHistory',
        ),
    ]
