# Generated by Django 5.2.1 on 2025-06-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methods', '0002_delete_calculationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_expression', models.CharField(help_text='La expresión de la función utilizada', max_length=255)),
                ('method_name', models.CharField(help_text='Nombre del método numérico (Bisección, Newton-Raphson, etc.)', max_length=50)),
                ('tolerance', models.FloatField(help_text='La tolerancia utilizada para el cálculo')),
                ('max_iterations', models.IntegerField(help_text='El número máximo de iteraciones permitidas')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cálculo')),
                ('a_value', models.FloatField(blank=True, help_text="Valor 'a' para Bisección", null=True)),
                ('b_value', models.FloatField(blank=True, help_text="Valor 'b' para Bisección", null=True)),
                ('initial_guess_value', models.FloatField(blank=True, help_text='Valor de estimación inicial (x₀)', null=True)),
                ('derivative_expression', models.CharField(blank=True, help_text='Expresión de la primera derivada', max_length=255, null=True)),
                ('second_derivative_expression', models.CharField(blank=True, help_text='Expresión de la segunda derivada', max_length=255, null=True)),
                ('result_value', models.FloatField(blank=True, help_text='La raíz aproximada encontrada', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el cálculo falló', null=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
    ]
